# .github/workflows/release-please-main.yml
name: Create Release PR - Main

on:
  workflow_dispatch: {} # manual trigger; pick branch in the UI
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Release Please - Main
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          target-branch: main
          config-file: releases/main/release-please-config.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          manifest-file: releases/main/.release-please-manifest.json
