# .github/workflows/release-please-dev.yml
name: Create Release PR - Dev

on:
  workflow_dispatch: {} # manual trigger; pick branch in the UI
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      - name: Release Please - Dev
        id: rp
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config-dev.json
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          manifest-file: .release-please-manifest.json
